const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env'), override: true });
console.log('env file loaded', path.join(__dirname,'.env'));
console.log('DB_ROOT_USER', process.env.DB_ROOT_USER);
console.log('DB_ROOT_PASSWORD', process.env.DB_ROOT_PASSWORD);
console.log('DB_USER', process.env.DB_USER);
console.log('DB_PASSWORD', process.env.DB_PASSWORD);
console.log('DB_HOST', process.env.DB_HOST);
console.log('DB_PORT', process.env.DB_PORT);
console.log('DB_NAME', process.env.DB_NAME);
