-- MySQL — QL Nhà hàng Golden Taste (chuyển từ QL_cuahanggoldentaste.sql)
CREATE DATABASE IF NOT EXISTS ql_golden_taste
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ql_golden_taste;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CHITIET_HD;
DROP TABLE IF EXISTS HOADON;
DROP TABLE IF EXISTS DINHMUC;
DROP TABLE IF EXISTS CHUC_NANG;
DROP TABLE IF EXISTS NHATKY;
DROP TABLE IF EXISTS MONAN;
DROP TABLE IF EXISTS NGUYENLIEU;
DROP TABLE IF EXISTS KHACHHANG;
DROP TABLE IF EXISTS NHANVIEN;
DROP TABLE IF EXISTS BAN;
DROP TABLE IF EXISTS LOAIMON;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE LOAIMON (
  maLOAI CHAR(5) NOT NULL PRIMARY KEY,
  tenLOAI VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MONAN (
  maMON CHAR(5) NOT NULL PRIMARY KEY,
  tenMON VARCHAR(100) NOT NULL UNIQUE,
  donGIA DECIMAL(18,0) NOT NULL,
  donVITINH VARCHAR(20) NOT NULL,
  trangthaiMON VARCHAR(20) NOT NULL,
  maLOAI CHAR(5) NOT NULL,
  CONSTRAINT FK_MONAN_LOAIMON FOREIGN KEY (maLOAI) REFERENCES LOAIMON(maLOAI)
);

CREATE TABLE BAN (
  maBAN CHAR(5) NOT NULL PRIMARY KEY,
  tenBAN VARCHAR(20) NOT NULL UNIQUE,
  viTRI VARCHAR(50) NOT NULL,
  sucCHUA INT NOT NULL,
  trangthaiBAN VARCHAR(20) NOT NULL DEFAULT 'Trống'
);

CREATE TABLE NHANVIEN (
  maNV CHAR(5) NOT NULL PRIMARY KEY,
  hotenNV VARCHAR(100) NOT NULL,
  ngaySINH DATE NOT NULL,
  gioiTINH VARCHAR(10) NOT NULL,
  SDT VARCHAR(10) NOT NULL UNIQUE,
  emailNV VARCHAR(100) NOT NULL UNIQUE,
  chucVU VARCHAR(50) NOT NULL,
  luongCB DECIMAL(18,0) NOT NULL DEFAULT 4420000,
  matKhauHash VARCHAR(255) NULL
);

CREATE TABLE KHACHHANG (
  maKH CHAR(5) NOT NULL PRIMARY KEY,
  tenKH VARCHAR(100) NOT NULL,
  SDT VARCHAR(10) NOT NULL UNIQUE,
  ngayDANGKY DATE NOT NULL DEFAULT (CURDATE()),
  diemTICHLUY INT NOT NULL DEFAULT 0
);

CREATE TABLE HOADON (
  maHD CHAR(10) NOT NULL PRIMARY KEY,
  ngayLAP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tongTIEN DECIMAL(18,0) NOT NULL DEFAULT 0,
  trangthaiHD VARCHAR(30) NOT NULL,
  daIN TINYINT(1) NOT NULL DEFAULT 0,
  maNV CHAR(5) NOT NULL,
  maBAN CHAR(5) NOT NULL,
  maKH CHAR(5) NULL,
  CONSTRAINT FK_HOADON_NV FOREIGN KEY (maNV) REFERENCES NHANVIEN(maNV),
  CONSTRAINT FK_HOADON_BAN FOREIGN KEY (maBAN) REFERENCES BAN(maBAN),
  CONSTRAINT FK_HOADON_KH FOREIGN KEY (maKH) REFERENCES KHACHHANG(maKH)
);

CREATE TABLE CHITIET_HD (
  maCTHD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  maHD CHAR(10) NOT NULL,
  maMON CHAR(5) NOT NULL,
  soLUONG INT NOT NULL,
  giaLUCBAN DECIMAL(18,0) NOT NULL,
  trangthaiQT VARCHAR(50) NOT NULL DEFAULT 'Chờ cung ứng',
  thanhTIEN DECIMAL(18,0) GENERATED ALWAYS AS (soLUONG * giaLUCBAN) STORED,
  CONSTRAINT FK_CTHD_HD FOREIGN KEY (maHD) REFERENCES HOADON(maHD) ON DELETE CASCADE,
  CONSTRAINT FK_CTHD_MON FOREIGN KEY (maMON) REFERENCES MONAN(maMON)
);

CREATE TABLE NGUYENLIEU (
  maNL CHAR(5) NOT NULL PRIMARY KEY,
  tenNL VARCHAR(100) NOT NULL UNIQUE,
  slTON DOUBLE NOT NULL DEFAULT 0,
  donVITINH VARCHAR(20) NOT NULL
);

CREATE TABLE DINHMUC (
  maMON CHAR(5) NOT NULL,
  maNL CHAR(5) NOT NULL,
  hamLUONG DOUBLE NOT NULL,
  PRIMARY KEY (maMON, maNL),
  CONSTRAINT FK_DM_MON FOREIGN KEY (maMON) REFERENCES MONAN(maMON),
  CONSTRAINT FK_DM_NL FOREIGN KEY (maNL) REFERENCES NGUYENLIEU(maNL)
);

CREATE TABLE CHUC_NANG (
  maCN CHAR(6) NOT NULL PRIMARY KEY,
  maTrang VARCHAR(30) NOT NULL UNIQUE,
  tenCN VARCHAR(120) NOT NULL,
  icon VARCHAR(12) NOT NULL DEFAULT '📌',
  moTa TEXT NOT NULL,
  vaiTroPhep VARCHAR(200) NOT NULL,
  apiMoTa TEXT NULL,
  thuTu INT NOT NULL DEFAULT 0,
  hienThi TINYINT(1) NOT NULL DEFAULT 1,
  capNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE NHATKY (
  maNK INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  thoiGIAN DATETIME DEFAULT CURRENT_TIMESTAMP,
  maNV CHAR(5) NULL,
  hanhDONG VARCHAR(50) NULL,
  tenBANG VARCHAR(50) NULL,
  noidungCU TEXT NULL,
  noidungMOI TEXT NULL,
  ghiCHU VARCHAR(200) NULL
);
